name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # also executable manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: build dependencies
        run: nix build path://$PWD/

      - name: python3 --version
        run: PATH="$PWD/result/bin" python3 --version
      - name: awk --version
        run: PATH="$PWD/result/bin" awk --version
      - name: sh --version
        run: PATH="$PWD/result/bin" sh --version
      - name: sha256sum --version
        run: PATH="$PWD/result/bin" sha256sum --version
      - name: sqlite3 --version
        run: PATH="$PWD/result/bin" sqlite3 --version
      - name: git --version
        run: PATH="$PWD/result/bin" git --version

      - name: Run tests
        run: PATH="$PWD/result/bin" python3 ./test.py
      - name: Run tests
        run: PATH="$PWD/result/bin" python3 ./test.py
      - uses: actions/upload-artifact@v2
        with:
          name: debug-git.tar.gz
          path: /tmp/debug-git.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: debug-sql.tar.gz
          path: /tmp/debug-sql.tar.gz
